version: '3.8'

services:
  superset:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: superset
    environment:
      - LOAD_EXAMPLES=yes
      - SUPERSET_CONFIG_PATH=/app/superset_config.py
      - SUPERSET_SECRET_KEY=your_secret_key_here
      - SUPERSET_DATABASE_HOST=superset_db
      - SUPERSET_DATABASE_USER=superset
      - SUPERSET_DATABASE_PASSWORD=superset
      - SUPERSET_DATABASE_DB=superset
    ports:
      - "8088:8088"
    depends_on:
      - superset_db
    restart: always

  superset_db:
    image: postgres:13
    container_name: superset_db
    environment:
      POSTGRES_USER: superset
      POSTGRES_PASSWORD: superset
      POSTGRES_DB: superset
    volumes:
      - superset_db_data:/var/lib/postgresql/data
    restart: always

  clickhouse:
    image: yandex/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123" # HTTP port for ClickHouse
      - "9000:9000" # Native port for ClickHouse
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    restart: always

volumes:
  superset_db_data:
  clickhouse_data: